# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1040)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1920, 1040))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:0.174, y2:0, stop:0 rgba(0, 223, 255, 255), stop:0.517413 rgba(170, 255, 255, 255), stop:1 rgba(133, 215, 255, 255));}")
        self.widget.setObjectName("widget")
        self.loginlbl = QtWidgets.QLabel(self.widget)
        self.loginlbl.setGeometry(QtCore.QRect(1210, 70, 401, 141))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(48)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginlbl.setFont(font)
        self.loginlbl.setStyleSheet("font: 48pt \"Lucida Calligraphy\";")
         self.loginlbl.setObjectName("loginlbl")
        self.siginlbl = QtWidgets.QLabel(self.widget)
        self.siginlbl.setGeometry(QtCore.QRect(1030, 200, 591, 91))
        self.siginlbl.setStyleSheet("font: 20pt \"Lucida Calligraphy\";")
        self.siginlbl.setObjectName("siginlbl")
        self.loginbtn = QtWidgets.QPushButton(self.widget)
        self.loginbtn.setGeometry(QtCore.QRect(1140, 680, 351, 71))
        self.loginbtn.setStyleSheet("QPushButton\n"
"{\n"
"border-radius:30px;\n"
"background-color:qlineargradient(spread:pad, x1:0.203592, y1:0.955, x2:0.786, y2:0.346682, stop:0 rgba(6, 224, 255, 255), stop:0.517413 rgba(170, 255, 255, 255), stop:1 rgba(34, 182, 255, 255));\n"
"font: 20pt \"Lucida Calligraphy\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border-radius:30px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0.102318, stop:0 rgba(6, 24, 255, 255), stop:0.517413 rgba(66, 252, 255, 255), stop:1 rgba(0, 55, 255, 255));\n"
"font: 20pt \"Lucida Calligraphy\";\n"
"}")
        self.loginbtn.setDefault(False)
        self.loginbtn.setObjectName("loginbtn")
        self.Usernameledit = QtWidgets.QLineEdit(self.widget)
        self.Usernameledit.setGeometry(QtCore.QRect(1000, 360, 641, 71))
        self.Usernameledit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(103, 215, 255);\n"
"font: 12pt \"Lucida Bright\";}\n"
"QLineEdit:focus{\n"
"border:2px solid #FBAD25;\n"
"background-color:rgb(0, 255, 255);\n"
"font: 12pt \"Lucida Bright\";}")
        self.Usernameledit.setText("")
        self.Usernameledit.setObjectName("Usernameledit")
        self.Passwordledit = QtWidgets.QLineEdit(self.widget)
        self.Passwordledit.setGeometry(QtCore.QRect(1000, 530, 641, 71))
        self.Passwordledit.setStyleSheet("QLineEdit{\n"
"background-color:rgb(103, 215, 255);\n"
"font: 12pt \"Lucida Bright\";}\n"
"QLineEdit:focus{\n"
"border:2px solid #FBAD25;\n"
"background-color:rgb(0, 255, 255);\n"
"font: 12pt \"Lucida Bright\";}")
        self.Passwordledit.setObjectName("Passwordledit")
        self.usernamelbl = QtWidgets.QLabel(self.widget)
        self.usernamelbl.setGeometry(QtCore.QRect(1000, 310, 181, 31))
        self.usernamelbl.setStyleSheet("font: 16pt \"Lucida Calligraphy\";")
        self.usernamelbl.setObjectName("usernamelbl")
        self.passwordlbl = QtWidgets.QLabel(self.widget)
        self.passwordlbl.setGeometry(QtCore.QRect(1000, 480, 181, 31))
        self.passwordlbl.setStyleSheet("font: 16pt \"Lucida Calligraphy\";")
        self.passwordlbl.setObjectName("passwordlbl")
        self.errorlineedt = QtWidgets.QLabel(self.widget)
        self.errorlineedt.setGeometry(QtCore.QRect(1000, 610, 481, 51))
        self.errorlineedt.setStyleSheet("font: italic 12pt \"Lucida Bright\";color:rgb(244, 55, 58);")
        self.errorlineedt.setText("")
        self.errorlineedt.setObjectName("errorlineedt")
        self.imglbltwo = QtWidgets.QLabel(self.widget)
        self.imglbltwo.setGeometry(QtCore.QRect(30, 310, 761, 511))
        self.imglbltwo.setObjectName("imglbltwo")
        self.imglbl = QtWidgets.QLabel(self.widget)
        self.imglbl.setGeometry(QtCore.QRect(580, 40, 331, 331))
        self.imglbl.setObjectName("imglbl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loginlbl.setText(_translate("Dialog", "Login"))
        self.siginlbl.setText(_translate("Dialog", "Sign in to your existing account"))
        self.loginbtn.setText(_translate("Dialog", "Log in"))
        self.usernamelbl.setText(_translate("Dialog", "Email-ID"))
        self.passwordlbl.setText(_translate("Dialog", "Password"))
        self.imglbltwo.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/img/output-onlinepngtools.png\"/></p></body></html>"))
        self.imglbl.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/img/login-icon-3060.png\"/></p></body></html>"))
import abc_rc
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
