# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginOptionMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1040)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1920, 1040))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.011, x2:0.99, y2:1, stop:0 rgba(0, 55, 255, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.widget.setObjectName("widget")
        self.welcomelbl = QtWidgets.QLabel(self.widget)
        self.welcomelbl.setGeometry(QtCore.QRect(550, -260, 1301, 881))
        self.welcomelbl.setStyleSheet("font: 48pt \"Lucida Calligraphy\";color: rgb(255, 255, 255);")
        self.welcomelbl.setObjectName("welcomelbl")
        self.lgorcrlbl = QtWidgets.QLabel(self.widget)
        self.lgorcrlbl.setGeometry(QtCore.QRect(750, 230, 551, 81))
        self.lgorcrlbl.setStyleSheet("font: 20pt \"Lucida Calligraphy\";color:white;")
        self.lgorcrlbl.setObjectName("lgorcrlbl")
        self.loginbtn = QtWidgets.QPushButton(self.widget)
        self.loginbtn.setGeometry(QtCore.QRect(740, 410, 351, 71))
        self.loginbtn.setStyleSheet("border-radius:30px;\n"
"background-color:rgb(236, 236, 236);\n"
"font: 20pt \"Lucida Calligraphy\";")
        self.loginbtn.setDefault(False)
        self.loginbtn.setObjectName("loginbtn")
        self.imglbl = QtWidgets.QLabel(self.widget)
        self.imglbl.setGeometry(QtCore.QRect(-30, 580, 951, 511))
        self.imglbl.setObjectName("imglbl")
        self.imglbl2 = QtWidgets.QLabel(self.widget)
        self.imglbl2.setGeometry(QtCore.QRect(1200, 400, 1121, 671))
        self.imglbl2.setObjectName("imglbl2")
        self.logo = QtWidgets.QLabel(self.widget)
        self.logo.setGeometry(QtCore.QRect(1690, -40, 361, 311))
        self.logo.setObjectName("logo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcomelbl.setText(_translate("Dialog", "Hotel Royal Galaxy"))
        self.lgorcrlbl.setText(_translate("Dialog", "The Best Place To Be ..."))
        self.loginbtn.setText(_translate("Dialog", "Log in"))
        self.imglbl.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/img/htl.png\"/></p></body></html>"))
        self.imglbl2.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/img/htl2.png\"/></p></body></html>"))
        self.logo.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/img/Royal_Classic_Hotel_Logo11.png\"/></p></body></html>"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
